runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker main:app
# entrypoint: gunicorn -b :8080 -k eventlet main:app

runtime_config:
  python_version: 3.7
network:
  session_affinity: true


# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 3
#   cool_down_period_sec: 60
#   cpu_utilization:
#     target_utilization: 0.5

# resources:
#   cpu: 4
#   memory_gb: 2
#   disk_size_gb: 10

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
